# Generated by Django 5.2.1 on 2025-05-26 12:42

from django.db import migrations

def create_job_roles(apps, schema_editor):
    JobRole = apps.get_model('accounts', 'JobRole')
    JobRole.objects.bulk_create([
        JobRole(title='Software Engineer', icon='💻'),
        JobRole(title='Data Analyst', icon='📊'),
        JobRole(title='Product Manager', icon='🧭'),
        JobRole(title='AI Researcher', icon='🧠'),
        JobRole(title='Backend Developer', icon='🛠️'),
        JobRole(title='DevOps Engineer', icon='⚙️'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_job_roles),
    ]
