# Generated by Django 5.2.1 on 2025-05-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_interviewsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.jobrole'),
        ),
    ]
