# Generated by Django 5.2.1 on 2025-05-30 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_aiquestionsuggestion_interviewquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewanswer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='answers/videos/'),
        ),
    ]
